Testing
ONSdigital/address-index-ui pull request #4
Opened 2021-06-09 14:49 UTC by Felixim0

2021-06-09 16:47 UTC, SammyPoot requested changes

2021-06-09 16:47 UTC, SammyPoot commented on tests/test_flaskr.py
> +    db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
Our app isn't called `flaskr`, so I'm unsure how this code could be working.

2021-06-09 16:47 UTC, SammyPoot commented on tests/test_flaskr.py
> +    db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
Perhaps this should be `aims_ui`

2021-06-10 09:25 UTC, Felixim0 commented on tests/test_flaskr.py
> +    db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
Updated and tested

2021-06-10 11:31 UTC, SammyPoot approved these changes

2021-06-10 11:57 UTC, merged